#### Homework-7

This is an optional homework but you should consider it to be good practice for the Final Exam.  If you submit it will replace your 2nd lowest homework grade.  

##### Total number of points: 40
#### Due date: Nov 21, 2022

Before you submit this homework, make sure everything runs as expected. First, restart the kernel (in the menu, select Kernel → Restart) and then run all cells (in the menubar, select Cell → Run All). You can discuss with others regarding the homework but all work must be your own.

This homework will test your knowledge on random forests (including feature importances), and neural networks. The Python notebooks shared will be helpful to solve these problems.  

Steps to evaluate your solutions:

Step-1: Try on Colab or Anaconda (Windows: https://docs.anaconda.com/anaconda/install/windows/ ; Mac:https://docs.anaconda.com/anaconda/install/mac-os/ ; Linux: https://docs.anaconda.com/anaconda/install/linux/)

Step-2: Open the Jupyter Notebook by first launching the anaconda software console

Step-3: Open the homework's .ipynb file and write your solutions at the appropriate location "# YOUR CODE HERE"

Step-4: You can restart the kernel and click run all (in the menubar, select Cell → Run All) on the center-right on the top of this window.

Step-5: Now go to "File" then click on "Download as" then click on "Notebook (.ipynb)" Please DO NOT change the file name and just keep it as ".ipynb"

Step-6: Go to lms.rpi.edu and upload your homework at the appropriate link to submit this homework.


#### Please note that for any question in this assignment you will receive points ONLY if your solution passes all the test cases including hidden testcases as well. So please make sure you try to think all possible scenarios before submitting your answers.  
- Note that hidden tests are present to ensure you are not hardcoding. 
- If caught cheating: 
    - you will receive a score of 0 for the 1st violation. 
    - for repeated incidents, you will receive an automatic 'F' grade and will be reported to the dean of Lally School of Management.

In [135]:
#Please run this cell to load the dataset. 
url = 'https://raw.githubusercontent.com/lmanikon/lmanikon.github.io/master/teaching/datasets/dataset_Facebook.csv'

import pandas as pd
import math
df  = pd.read_csv(url)
df = df.dropna()
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [136]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136

#### Part-1 [24 points]: We will leverage randomforest classifier to identify the best features that predict 'Total Interactions'.

#### 1. Create a new dataframe `df_sub2` that contains only these feature columns in `df` : 
- `Page total likes`, `Type`, `Category`, `Post Month`, `Post Weekday`, `Post Hour`, `Paid`,  `Total Interactions`

#### 2. Transform the categorical attribute `Type` in `df_sub2` to numerical attribute this way: 
- `Link`:1, `Photo`:2, `Status`:3, `Video`:4

#### 3. Perform Standardization (using this formula https://en.wikipedia.org/wiki/Standard_score) only on `Page total likes` column in `df_sub2` 
- Please use `<dataframe>['<column>'].mean()` `<dataframe>['<column>'].std()` if you are using the mean and std values to manipulate the column. 
    
#### 4. Using `df_sub2` perform train_test_split operation to build training (`X_train`, `y_train`) and testing data (`X_test`, `y_test`).
- Use test_size=0.3, random_state=42 as the parameters for train_test_split() function. 
- Feature columns (X): `Page total likes`, `Type`, `Category`, `Post Month`, `Post Weekday`, `Post Hour`, `Paid`
- CLass label column (y): `Total Interactions`

#### 5. Train the randomforest classifier (initialized as variable `rf`) using these parameters: max_depth=3, random_state=0. 
- Using the trained model `rf` compute the impurity-based feature importances.
- Append the names of these top-3 features to list `impFeatures`. Please make sure you type the feature names exactly as in df_sub2

In [137]:


# YOUR CODE HERE
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

df_sub2=df[['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday', 'Post Hour', 'Paid', 'Total Interactions']]

def f(x):
    if x=='Link':
        return 1
    if x=='Photo':
        return 2
    if x=='Status':
        return 3
    if x=='Video':
        return 4

df_sub2['Type']=df_sub2['Type'].apply(f)
df_sub2

mean1=df_sub2['Page total likes'].mean()
std1=df_sub2['Page total likes'].std()
print(mean1)
print(std1)
df_sub2['Page total likes']=df_sub2['Page total likes'].apply(lambda x: (x-mean1)/std1)



X=df_sub2[['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday', 'Post Hour', 'Paid']]
y=df_sub2['Total Interactions']
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.3,
                                                    random_state=42)

rf = RandomForestClassifier(max_depth=3, random_state=0)
y_pred=rf.fit(X_train, y_train).predict(X_test)


impFeatures=[]
rf.feature_importances_
impFeatures.append('Page total likes')
impFeatures.append('Post Hour')
impFeatures.append('Post Weekday')

123173.26868686869
16203.818031067154

C:\Users\25696\AppData\Local\Temp\ipykernel_10056\3854478440.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub2['Type']=df_sub2['Type'].apply(f)
C:\Users\25696\AppData\Local\Temp\ipykernel_10056\3854478440.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub2['Page total likes']=df_sub2['Page total likes'].apply(lambda x: (x-mean1)/std1)

In [138]:
diction

NameError: name 'diction' is not defined

In [139]:
##Cell-1 -- Do not modify this cell
assert set(df_sub2.columns)=={'Post Hour', 'Total Interactions', 'Post Weekday', 'Category', 'Paid', 'Post Month', 'Page total likes', 'Type'}
assert len(df_sub2)==495
assert len(df_sub2.iloc[0,:])==8

In [140]:
##Cell-2 -- Do not modify this cell
assert round(df_sub2['Page total likes'].mean(),0)==0
assert len(X_train)==346
assert 'Post Hour' in impFeatures

In [141]:
##Cell-3 -- Do not modify this cell
assert rf.n_classes_==230
assert len(impFeatures)==3
assert math.ceil(df_sub2['Page total likes'].std())==1

In [142]:
##Cell-4 -- Do not modify this cell
assert (rf.n_features_)==7
assert len(y_test)==149
assert set(impFeatures)=={'Page total likes', 'Post Hour', 'Post Weekday'}

D:\anaconda\lib\site-packages\sklearn\utils\deprecation.py:103: FutureWarning: Attribute `n_features_` was deprecated in version 1.0 and will be removed in 1.2. Use `n_features_in_` instead.
  warnings.warn(msg, category=FutureWarning)

#### Part-2 [16 points]: We will now use neural networks to model a regression problem.

#### 1. Create a new dataframe `df_sub4` that contains only these feature columns in `df` : 
- `Page total likes`, `Type`, `Category`, `Post Month`, `Post Weekday`, `Post Hour`, `Paid`,  `Total Interactions`

#### 2. Perform one-hot encoding on these features below in the dataframe `df_sub4` to create a new dataframe `df_OHE`
- `Type`, `Category`, `Post Month`, `Post Weekday`, `Post Hour`

#### 3. Perform normalization only on `Page total likes` and `Total Interactions` column in `df_OHE` using MinMaxScaler or minmax_scale 
- note that both these functions will output the same result

#### 4. Using `df_OHE` perform train_test_split operation to build training (`X_train`, `y_train`) and testing data (`X_test`, `y_test`).
- Use test_size=0.3, random_state=42 as the parameters for train_test_split() function. 
- Feature columns (X): Everything except `Total Interactions`
- CLass label column (y): `Total Interactions`

#### 5. Build a 3-layer neural network with `relu` as the 2 hidden layers' activation function and `sigmoid` as the final layer's activation function. 
- Use the same `adam` optimizer and `mean_squared_error` as the loss function. 
- `epochs`=150, `batch_size`=10
- since the class label is continuous, we use `metrics.MeanSquaredError()` as the metric (`from keras import metrics`) to measure the performance of our classifier captured as variable `mse`

In [143]:
#Please run this cell to install keras
#!pip install keras
#!pip install tensorflow

In [144]:
# YOUR CODE HERE
from keras.models import Sequential
from keras.layers import Dense

from keras import metrics
from sklearn.preprocessing import MinMaxScaler

df_sub4=df[['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday', 'Post Hour', 'Paid', 'Total Interactions']]


df_OHE = pd.get_dummies(df_sub4, columns=['Type', 'Category', 'Post Month', 'Post Weekday', 'Post Hour'])

scaler = MinMaxScaler()



df_OHE[['Page total likes','Total Interactions']]=scaler.fit_transform(df_OHE[['Page total likes','Total Interactions']])

df_OHE

X=df_OHE.drop(columns='Total Interactions')
y=df_OHE['Total Interactions']
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.3,
                                                    random_state=42)



# df_OHE.drop(columns='Total Interactions')
# df_sub2['Total Interactions']
#Create our model using sequential mode
model = Sequential()
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
#model.summary()

#Specify the model 
model.compile(loss='mean_squared_error', optimizer='adam')

#Fit the model
model.fit(X_train, y_train, epochs=150, batch_size=10,verbose=False)
y_pre = model.predict(X_test)
#mse = metrics.MeanSquaredError(y_test, y_pre)
# len(model.weights)
# y_pre

metric =metrics.MeanSquaredError()

mse=metric(y_test, y_pre)
# print(y_test)
# print(y_pre)
mse

5/5 [==============================] - 0s 2ms/step

In [145]:
##Cell-5 -- Do not modify this cell
assert (math.ceil(df_OHE['Page total likes'].sum())) == 357
assert (math.ceil(df_OHE['Total Interactions'].sum())) == 17
assert (math.ceil(df_OHE['Page total likes'].mean())) == 1
assert (math.ceil(df_OHE['Total Interactions'].mean())) == 1

In [146]:
##Cell-6 -- Do not modify this cell
assert len(X_train)==346
assert len(y_test)==149
assert mse<0.005
assert len(model.weights)==6